name: Python CI/CD

on:
  push:
  pull_request:

jobs:
  test-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest

      - name: Package Python application
        run: |
          mkdir package
          cp calculator.py package/
          cp test_calculator.py package/
          cp README.md package/
          cd package
          zip -r ../python-calculator.zip .
      - name: Package Python application
        run: |
          mkdir package
          cp calculator.py package/
          cp test_calculator.py package/
          cp README.md package/
          cd package
          zip -r ../python-calculator.zip .

      - name: Upload application package
        uses: actions/upload-artifact@v4
        with:
          name: python-calculator
          path: python-calculator.zip
